### ISSUE TITLE
Missing Image in Lab 7 - ./media/l07_add_access_policy_principal.png

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.de-de#8]
In instructions document: https://raw.githubusercontent.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.de-de/main/Instructions/Labs/AZ-204_lab_07.md

We are missing file: ./media/l07_add_access_policy_principal.png

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Query](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPlRydWU8L0xGTz48SUQ%2bRmFsc2U8L0lEPjxFTEM%2bRmFsc2U8L0VMQz48QU1QPkZhbHNlPC9BTVA%2bPFNPSFJJUj5GYWxzZTwvU09IUklSPjxTSFJQPlRydWU8L1NIUlA%2bPFNBVE8%2bRmFsc2U8L1NBVE8%2bPFNBTE8%2bVHJ1ZTwvU0FMTz48UUU%2bPjI8L1FFPjxRVD4%2bPFFSIElkPSIxIiBDUElEPSIwIj5DdXJyZW50O0ZpbGVzO0hvc3QgQ29udGVudCBTdG9yZTtFcXVhbDtXV0w8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7SXRhbGlhbiAoSXRhbHkpPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQ29udGVudCBHcm91cDtFcXVhbDtMQUItQVotMjA0X01hc3RlcjwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b) missing - awaiting PM instructions
